version: "3"  
services:
    food-aggregator:
        build:
            context: .
            dockerfile: DockerFile
        image: food-aggregator
        container_name: food-aggregator-container
        ports:
            - '8080:8080'
        networks:
            - myNetwork
networks:
    myNetwork: 
